### ISSUE TITLE
Some remarks

### ISSUE THREAD

**Issue by barryvdh** [msurguy/laravel-shop-menu#2]
Hey,
Thanks for the example code. I did it somewhat similar, but instead of dropping, just use a save button and serialize/save the entire form at once, and created a Twig macro for menu builder :)

 I just have a few remarks/questions:
- You escape all input, ie. `e(Input::get('order'))`. But isn't this unneeded because of Laravels ORM? Isn't it more logical to escape when displaying data?
  - You use dropCallback, which isn't in the linked version of Nestable. What fork do you use/recommend, as the original project doesn't seem to be maintained?
  - Instead of buildMenu function directly, you could also create a method to build a tree, and use that to create your menu. This would make the buildMenu function a tiny bit simpler and you could use the same tree to build the front-end menu. (Just a suggestion)
  - Isn't it best practice to create links to actions (or named routes), and not just (`url('admin/menu/etc')`). Doesn't matter that much, but when you are creating a tutorial, might as well use best practices.

**Comment by msurguy** [comment]
To address your questions:
1) yes, the input doesn't need to be escaped, I just use that based on some bad experience I had with anything user-driven and user-submittable.
2) You're right, I forgot to mention about the particalar fork of Nestable, I had to search through lots of pull requests on that project to get the desired result. I now created a fork with the proper modifications: https://github.com/msurguy/Nestable
3) Definitely could be done, I just want to make my tutorials so simple and adaptable to other things that developers could see the process before packaging everything in a tiny little box that they could only see from the outside. I like to leave things in-progress for them to learn from it. This by no means is the final version that they should have in their product.
4) Actually I disagree with naming actions/routes. I haven't used it at all since I started with Laravel abt 2 years ago. In my opinion it doesn't help much to use named routes. (this is something that we just have to disagree on)

**Comment by mackhankins** [comment]
https://github.com/tchapi/Nestable  I'd love to have the noChildrenClass from this fork with yours, but I can't seem to get it together.

**Comment by mackhankins** [comment]
Did it in the controller, never mind.  Allows no children to be assigned for that category which is exactly what I was looking for.

``` php
    public function postIndex()
    {
        $source = e(Input::get('source'));
        $destination = e(Input::get('destination', 0));

        if($destination == 1) return false;
```

**Comment by msurguy** [comment]
@mack-hankins Very cool!
